-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN ICECREAM_INFO ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
  AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;